-- ====================================================================
-- QLIB QUANTITATIVE RECOMMENDATIONS SCHEMA
-- Project ID: <your-project-id>
-- Endpoint: https://<your-project-id>.supabase.co
--
-- Execute via Supabase CLI:
--   supabase db query --linked -f src/qlib/doc/supabase_schema.sql
-- Or paste into Supabase Web SQL Editor:
--   https://supabase.com/dashboard/project/<your-project-id>/sql/new
-- ====================================================================

-- --------------------------------------------------------------------
-- 1. Daily Recommendations Table (T+1 to T+2 Horizon)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.qlib_daily_top10_recommend (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trade_date DATE NOT NULL,
    date TIMESTAMP,
    target_date DATE,
    predicted_close NUMERIC(10, 2),
    target_date_close NUMERIC(10, 2),
    predicted_diff NUMERIC(10, 2),
    rank INTEGER NOT NULL,
    symbol TEXT NOT NULL,
    name TEXT NOT NULL,
    sector TEXT NOT NULL,
    setup_type TEXT NOT NULL,
    close_price NUMERIC(10, 2) NOT NULL,
    ret_1d NUMERIC(7, 4),
    ret_3d NUMERIC(7, 4),
    vol_surge NUMERIC(6, 2),
    clv NUMERIC(4, 2),
    rsi_7 NUMERIC(5, 2),
    alpha_score NUMERIC(6, 2) NOT NULL,
    stop_loss NUMERIC(10, 2) NOT NULL,
    target_t1 NUMERIC(10, 2) NOT NULL,
    rr_ratio NUMERIC(4, 1),
    market_regime TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_qlib_daily_date_symbol UNIQUE (trade_date, symbol)
);

-- Trigger to auto-compute predicted price difference:
-- predicted_diff = target_date_close - predicted_close (vs Point Forecast)
CREATE OR REPLACE FUNCTION update_qlib_daily_price_diff()
RETURNS TRIGGER AS $$
BEGIN
    IF NEW.target_date_close IS NOT NULL AND NEW.predicted_close IS NOT NULL THEN
        NEW.predicted_diff := ROUND((NEW.target_date_close - NEW.predicted_close)::numeric, 2);
    ELSE
        NEW.predicted_diff := NULL;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_qlib_daily_price_diff ON public.qlib_daily_top10_recommend;
CREATE TRIGGER trg_qlib_daily_price_diff
BEFORE INSERT OR UPDATE OF target_date_close, predicted_close
ON public.qlib_daily_top10_recommend
FOR EACH ROW
EXECUTE FUNCTION update_qlib_daily_price_diff();

CREATE INDEX IF NOT EXISTS idx_qlib_daily_trade_date ON public.qlib_daily_top10_recommend(trade_date);
CREATE INDEX IF NOT EXISTS idx_qlib_daily_exec_date ON public.qlib_daily_top10_recommend(date);
CREATE INDEX IF NOT EXISTS idx_qlib_daily_target_date ON public.qlib_daily_top10_recommend(target_date);
CREATE INDEX IF NOT EXISTS idx_qlib_daily_symbol ON public.qlib_daily_top10_recommend(symbol);
CREATE INDEX IF NOT EXISTS idx_qlib_daily_rank ON public.qlib_daily_top10_recommend(trade_date, rank);

-- --------------------------------------------------------------------
-- 2. Weekly Recommendations Table (1-Week Horizon: Monday to Friday)
-- --------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.qlib_weekly_top10_recommend (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    week_start_date DATE NOT NULL,
    rank INTEGER NOT NULL,
    symbol TEXT NOT NULL,
    name TEXT NOT NULL,
    sector TEXT NOT NULL,
    close_price NUMERIC(10, 2) NOT NULL,
    ret_5d NUMERIC(7, 4),
    ret_20d NUMERIC(7, 4),
    vol_ratio NUMERIC(6, 2),
    rsi_14 NUMERIC(5, 2),
    alpha_score NUMERIC(6, 2) NOT NULL,
    stop_loss NUMERIC(10, 2) NOT NULL,
    target_price NUMERIC(10, 2) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_qlib_weekly_date_symbol UNIQUE (week_start_date, symbol)
);

CREATE INDEX IF NOT EXISTS idx_qlib_weekly_date ON public.qlib_weekly_top10_recommend(week_start_date);
CREATE INDEX IF NOT EXISTS idx_qlib_weekly_symbol ON public.qlib_weekly_top10_recommend(symbol);
CREATE INDEX IF NOT EXISTS idx_qlib_weekly_rank ON public.qlib_weekly_top10_recommend(week_start_date, rank);

-- --------------------------------------------------------------------
-- 3. Row Level Security (RLS) & Policies
-- --------------------------------------------------------------------
ALTER TABLE public.qlib_daily_top10_recommend ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.qlib_weekly_top10_recommend ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "anon_qlib_daily_policy" ON public.qlib_daily_top10_recommend;
CREATE POLICY "anon_qlib_daily_policy" ON public.qlib_daily_top10_recommend
    FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);

DROP POLICY IF EXISTS "anon_qlib_weekly_policy" ON public.qlib_weekly_top10_recommend;
CREATE POLICY "anon_qlib_weekly_policy" ON public.qlib_weekly_top10_recommend
    FOR ALL TO anon, authenticated USING (true) WITH CHECK (true);
